/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'christoph' at '9/29/17, 7:26 AM' with Gradle 2.10
 *
 * @author christoph, @date 9/29/17, 7:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
